# Generated by Django 3.0.3 on 2022-06-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='organism',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='organism_clade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organism',
            name='organism_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pfamdes',
            name='domain',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proteinsequence',
            name='protein',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
